### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by skaldebane**
Small grammar and structure improvements.

### CODE REVIEW

**Review by adamglin0 — APPROVED** [review]
LGTM

**Comment by skaldebane** [comment]
Hey @adamglin0, thanks for the invitiation!

Not related to this PR, but what is your policy on merging changes / reviewing / releases?
Just so we're on the same page :D

**Comment by adamglin0** [comment]
> Hey @adamglin0, thanks for the invitiation!
> 
> Not related to this PR, but what is your policy on merging changes / reviewing / releases? Just so we're on the same page :D

Because initially this library was only for personal use, I am very happy to see the increase in stars, so I will also start considering some template processes and release standards.

1. Merge Requests: Currently, the only requirement for merge requests is that they can pass tests. Additionally, they should prevent obvious vulnerabilities and performance issues. Subsequent optimizations can be addressed through new PRs.

2. Reviewing: I welcome reviews and suggestions from anyone. Any opinions can be raised.

3. Release: There are no specific requirements for this. It seems there isn't much that can be done. After supporting Inner Shadow, I plan to do some simple optimizations for the project and then release version 1.0.0.

**Comment by adamglin0** [comment]
Any content related to the entire project is welcome for anyone to provide any feedback.

**Pull request merged**
